name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean build jibDockerBuild
    - name: Login to GitHub Docker Registry
      run: docker login docker.io --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
          DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
    - name: Push Docker Image
      run: docker push greencloud/greencloud-server-application:latest
